### ISSUE TITLE
masscan.masscan.NetworkConnectionError: network is unreachable.

### ISSUE THREAD

**Issue by FuckAllWorld** [MyKings/python-masscan#28]
[DEBUG] [masscan.py 10 line] Scan parameters: "masscan -oX - x.x.x.x/24 -p 22 --max-rate 1000"
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/masscan/masscan.py", line 384, in analyse_masscan_xml_scan
    dom = ET.fromstring(self._masscan_last_output)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1334, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ppp.py", line 6, in <module>
    mas.scan(i.rstrip(), ports='22', arguments='--max-rate 1000')
  File "/usr/local/lib/python3.5/dist-packages/masscan/masscan.py", line 329, in scan
    masscan_warn_keep_trace=masscan_warn_keep_trace
  File "/usr/local/lib/python3.5/dist-packages/masscan/masscan.py", line 387, in analyse_masscan_xml_scan
    raise NetworkConnectionError("network is unreachable.")
masscan.masscan.NetworkConnectionError: network is unreachable.

if i set two port,everything is normal

[DEBUG] [masscan.py 10 line] Scan parameters: "masscan -oX - x.x.x.x/24 -p 22,80 --max-rate 1000"
{'masscan': {'scanstats': {'..............

**Comment by MyKings** [comment]
@FuckAllWorld 
Can you execute the `masscan -oX - x.x.x.x/24 -p 22 --max-rate 1000` command and see the results?

**Comment by FuckAllWorld** [comment]
yeah,but sometime:masscan.masscan.NetworkConnectionError: network is unreachable.i don't know why

**Comment by MyKings** [comment]
This error is that the `masscan` scan failed and no results were returned.

**Comment by FuckAllWorld** [comment]
I'sure is my network problem.
